# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/TimmyCore/TimmyCore/TimmyCore.cache/wt [current_project]
set_property parent.project_path E:/TimmyCore/TimmyCore/TimmyCore.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo e:/TimmyCore/TimmyCore/TimmyCore.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/RISCV_CORE/config.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/RISCV_CORE/ALU.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/timmy_core/MMU_timmy_stub_V2.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/RISCV_CORE/Shifter.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/RISCV_CORE/decode.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/RISCV_CORE/fence.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/timmy_core/mux_timmy.vhd
  E:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/imports/Ram2DdrXadc_RefComp/ram2ddrxadc.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/timmy_core/ram_controller_timmy.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/RISCV_CORE/regfile.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/timmy_core/sext_timmy.vhd
  C:/Users/Cesar/Documents/GitHub/CAV/Senior_Design_Capstone/timmy_core/TIMMYCORE_V2.vhd
}
read_ip -quiet e:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/ip/ddr/ddr.xci
set_property used_in_implementation false [get_files -all e:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr.xdc]
set_property used_in_implementation false [get_files -all e:/TimmyCore/TimmyCore/TimmyCore.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/TimmyCore/TimmyCore/TimmyCore.srcs/constrs_1/imports/XDC/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/TimmyCore/TimmyCore/TimmyCore.srcs/constrs_1/imports/XDC/Nexys4DDR_Master.xdc]


synth_design -top TIMMYCORE_V2 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TIMMYCORE_V2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TIMMYCORE_V2_utilization_synth.rpt -pb TIMMYCORE_V2_utilization_synth.pb"
